# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 80
  # Include code blocks
  code_blocks: false 
  # Include headings
  headings: false
  # Include headings
  headers: false
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false